name: Docs

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3
        with:
          hugo-version: latest
          extended: true
      - run: hugo --minify
        working-directory: docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/public
      - id: deployment
        uses: actions/deploy-pages@v4
